name: New-Features Workflow

on:
  issues:
    types: [opened]

jobs:
  label-feature:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add 'new application features' label to all new issues
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['new application features']
            })
